### ISSUE TITLE
gist_map piping?

### ISSUE THREAD

**Issue by sckott** [ropensci/gistr#24]
@karthik sorry to keep asking questions, but it looks like the file name for this fxn is only needed to append to the url (that is, no local file manipulation needed in the fxn). Can we just get that from the output of `gist_create()`?, and if so, then the output of `gist_create()` can be piped to `gist_map()` as it's first argument? Or are you trying to support if someone wants to use a local file too?

**Comment by sckott** [comment]
getting file name by doing e.g. `names(gist_id$files)`

**Comment by karthik** [comment]
Good question.That's how I originally had it but for some reason thought multiple files could be associated with the same gist. Will fix.

**Comment by sckott** [comment]
cool, thx

**Comment by karthik** [comment]
Actually, I still see the problem I had before. e.g.

```r
x <- gists("minepublic")
names(x[[1]]$files)
[1] "stuff.md" "zoo.json"
```

So there are two files with this gist. If I do `names(gist_id$files)`, and two are returned,  these two lines will fail:

```r
file <- names(gist_object$files)
assertthat::assert_that(has_extension(file, "geojson"))
```

that's why I was passing a file argument. Should I just check for `geojson`, and only plot those? 
What if there are more than one geojson? Map all of them?

**Comment by sckott** [comment]
i see. what if they can still be piped together, so the second argument to gist_map is the file name to use? and if they don't give a file name then you look for geojson files, map first one?, and warn/stop if no geojson files found
