### ISSUE TITLE
delete revisions 

### ISSUE THREAD

**Issue by helgasoft** [ropensci/gistr#81]
Was trying to use the library for **revision maintenance**.  Unfortunately individual gist revisions cannot be deleted.  Maybe a future enhancement..?

```r
gr1 <- gist('someID', 'someRevisionID')
gist_save(gr1, path = "C:/myGists")  # works ok, saves the revision only
gr1 %>% delete()    # deletes the entire gist!, not the revision only
```

**Comment by sckott** [comment]
thanks for this @helgasoft 

just so we're on the same page, are you hoping to delete the file on disk that `gist_save` creates? or a revision of a gist on your gists? I assume it's the latter

I've tried to see if the Github api would allow a revision id in a DELETE request but it doesn't seem to work, which is not surprising since the docs https://developer.github.com/v3/gists/#delete-a-gist only say that you can delete an entire gist
